In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
b = np.array([12,5,15,5,6,4,8,9,16,8,56,84,87,65,748,44,6,4])

In [7]:
b.reshape(9,2)

array([[ 12,   5],
       [ 15,   5],
       [  6,   4],
       [  8,   9],
       [ 16,   8],
       [ 56,  84],
       [ 87,  65],
       [748,  44],
       [  6,   4]])

In [8]:
b.reshape(6,3)

array([[ 12,   5,  15],
       [  5,   6,   4],
       [  8,   9,  16],
       [  8,  56,  84],
       [ 87,  65, 748],
       [ 44,   6,   4]])

In [22]:
b = b.reshape(3,6)
b

array([[ 12,   5,  15,   5,   6,   4],
       [  8,   9,  16,   8,  56,  84],
       [ 87,  65, 748,  44,   6,   4]])

In [16]:
c = np.array([12,5,15,5,6,4,8,9,16,8,56,84,87,65,748,44,6,4,3])

In [17]:
np.argsort(c)

array([18,  5, 17,  1,  3, 16,  4,  9,  6,  7,  0,  2,  8, 15, 10, 13, 11,
       12, 14])

In [18]:
np.argmin(c)

18

In [19]:
np.argmax(c)

14

In [23]:
np.argsort(b)

array([[5, 1, 3, 4, 0, 2],
       [0, 3, 1, 2, 4, 5],
       [5, 4, 3, 1, 0, 2]])

In [24]:
np.argsort(b, axis=0)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 2, 2],
       [2, 2, 2, 2, 1, 1]])