In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
              [4,5,6]])

In [3]:
a.sum(axis=0)

array([5, 7, 9])

In [4]:
a.sum(axis=1)

array([ 6, 15])

In [5]:
a.sum()

21

In [6]:
b = np.array([[7,8,9],
              [2,9,0]])

In [7]:
b.transpose()

array([[7, 2],
       [8, 9],
       [9, 0]])

In [8]:
np.dot(a, b.transpose())

array([[ 50,  20],
       [122,  53]])

In [9]:
#dir(np)

In [10]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [-54,  12,  26]])

In [11]:
c = np.array([[ -6,  12],[ -6,  3]])

In [12]:
d = np.array([[ -6,  1],[ -6,  1]])

In [13]:
np.cross(c,d)

array([66, 12])

In [14]:
np.sort(b)

array([[7, 8, 9],
       [0, 2, 9]])

In [15]:
np.sort(b, axis=0)

array([[2, 8, 0],
       [7, 9, 9]])

In [16]:
np.sort(b, axis=0, kind="mergesort") #kind is sorting method name

array([[2, 8, 0],
       [7, 9, 9]])

In [17]:
np.sort(b, axis=0, kind="quicksort")

array([[2, 8, 0],
       [7, 9, 9]])