## Basic Methods

In [1]:
import numpy as np
array1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype="int32")
print(array1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
array1.shape

(2, 5)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones(5).dtype

dtype('float64')

In [8]:
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)

In [10]:
array1*array1

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]], dtype=int32)

In [11]:
array1+array1

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]], dtype=int32)

In [12]:
array1-array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [13]:
array1**array1

array([[         1,          4,         27,        256,       3125],
       [     46656,     823543,   16777216,  387420489, 1410065408]],
      dtype=int32)

In [14]:
1/array1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

## Slicing

In [15]:
array2 = np.array([6,5,2,9,5,1])

In [16]:
arr = array2[3:6]

In [17]:
arr

array([9, 5, 1])

In [18]:
arr[2] = 10

In [19]:
arr

array([ 9,  5, 10])

In [20]:
array2

array([ 6,  5,  2,  9,  5, 10])

In [21]:
arr2 = array2[0:3].copy()

In [22]:
arr2

array([6, 5, 2])

In [23]:
arr2[2] = 20

In [24]:
arr2

array([ 6,  5, 20])

In [25]:
array2

array([ 6,  5,  2,  9,  5, 10])

In [26]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)

In [28]:
array1[0:1]

array([[1, 2, 3, 4, 5]], dtype=int32)

In [29]:
array1[0][3]

4

In [30]:
array1[0, 3]

4